### ISSUE TITLE
test_apps/workspace_minimal_d3d11_win fails to compile (orphaned XR_EXT_app_launcher.h since #308)

### ISSUE THREAD

**Issue by dfattal** [dfattal/openxr-3d-display#375]
## Summary

`test_apps/workspace_minimal_d3d11_win/main.cpp` does not compile. It still `#include`s the launcher extension header and resolves/exercises the launcher PFNs, but the runtime launcher (and `XR_EXT_app_launcher.h`) were **removed in #308** (`c74f1770b` — "remove runtime launcher; add input-grab + SBS overlay (spec 17→19)"). This is pre-existing — not caused by #370.

## Repro

```
scripts\build_windows.bat test-apps
```

```
main.cpp(49): fatal error C1083: Cannot open include file: 'openxr/XR_EXT_app_launcher.h': No such file or directory
```

## Details

The orphaned launcher surface in `main.cpp`:
- `#include <openxr/XR_EXT_app_launcher.h>` — L49 (header deleted in #308)
- PFN decls — L146–150 (`pfnClearLauncher`, `pfnAddLauncherApp`, `pfnSetLauncherVisible`, `pfnPollLauncherClick`, `pfnSetRunningTileMask`)
- get-proc lookups — L184–188
- launcher smoke-test block — L718–743 (`XrLauncherAppInfoEXT`, `xrClearLauncherAppsEXT`, etc.)

## CI impact

**None today.** `build-windows.yml`'s test-apps job only builds `cube_handle_d3d11_win`, so `main` CI stays green; the breakage is latent (only surfaces via local `build_windows.bat test-apps`, which builds every test app).

## Fix

Remove the launcher include + the 5 launcher PFNs (decls, lookups, and the L718–743 exercise) from the smoke test, so it again compiles and resolves only the live `XR_EXT_spatial_workspace` surface.

## Context

This smoke test is the canonical "resolve every workspace PFN + walk the lifecycle" coverage app. #370 (cursor-depth shell-ownership, spec 22) already touched it — it swapped the removed `xrWorkspaceHitTestEXT` for the new `xrSetWorkspaceCursorDepthEXT` — but intentionally left the #308 launcher fallout out of scope. This issue tracks that cleanup.
